name: Auto Merge Owner PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5.0.0

      - uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8
        run: flake8 --ignore=E501,E231 *.py tests/*.py

      - name: Run pylint
        run: pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py

      - name: Run unit tests
        run: python -m unittest --verbose --failfast

  merge:
    if: github.actor == 'runarion'
    needs: [lint]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: hmarr/auto-approve-action@v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
 
